### ISSUE TITLE
Not evident how to reference Entry or Chain

### ISSUE THREAD

**Issue by eolszewski** [PaulBernier/factomjs#2]
In the README, there are instructions for creating a chain as well as an entry, but there is no reference or import to these in the docs.

**Comment by eolszewski** [comment]
Simple update to `const { FactomCli, Entry, Chain } = require('factom');` would address this.

**Comment by PaulBernier** [comment]
Sure I can make that explicit. All functions and classes mentioned in the README can be imported via `require('factom');`. Thanks for the feedback.

**Comment by PaulBernier** [comment]
Updated in d06d4055f48cf2e7b1c6218a5664eb3d9528cc2d
