### ISSUE TITLE
 Error: Es32PjobTxPTd73dohEFRegMFRLv3X5kZ4FXEwtN8kE2pMDfeMym is not a valid address

### ISSUE THREAD

**Issue by eolszewski** [PaulBernier/factomjs#3]
Following the README, 
```
cli.add(chain, 'Es32PjobTxPTd73dohEFRegMFRLv3X5kZ4FXEwtN8kE2pMDfeMym');
```
produces this error.

Where is identifier coming from / how do I generate a valid one?

**Comment by eolszewski** [comment]
Seems like this is `ecAddress`, where do I find this address?

**Comment by eolszewski** [comment]
I assume this is the wallet address? I am running the wallet daemon and assumed that this would not need to be provided when creating the cli object with localhost:8089.

**Comment by AlexCarrithers** [comment]
That is just a nonsense private key that used as a placeholder in the readme. It does not satisfy the checksum which is why it throws an error. If you want to use that method, you will need to create a new private key. 

Public addresses begin with EC, private keys begin with ES.

**Comment by eolszewski** [comment]
Is there code for doing so, what curve do I use?

**Comment by AlexCarrithers** [comment]
I haven't used this area of the library yet, but I believe the best way to do it is to make a raw walletd api call. So something like this:

`const ecKeys = cli.walletdApi('generate-ec-address')`

You can see that API call here: https://docs.factom.com/api?json#generate-ec-address

And instruction on how to make raw API calls in FactomJS at the bottom of the README: https://github.com/PaulBernier/factomjs#raw-factomd-and-walletd-api-calls

**Comment by AlexCarrithers** [comment]
You are passing in the public address, but the initial example you posted from the README used the private key. The private key is also known as the 'secret', and it begins with _ES_.

In order to make an entry, you will also need to fund the corresponding public address (i.e. the string beginning EC that you posted above) with some entry credits.

**Comment by eolszewski** [comment]
It looks like this requires an address beginning with Fs.

Can you provide for me some psuedocode for the steps needing to be taken to store something on Factom?

At present, I have the factom daemon and wallet daemon running and have passed the localhost vars into the cli object.

If you could point to how to get he factoshis into an address and then into entry credits and how to track these, that would be very helpful.

Thank you

**Comment by drkatz** [comment]
Hey there @eolszewski ! Thanks for your interest in Factom and this lib.

The [Factom CLI Docs](https://docs.factom.com/cli#factom-cli-guides) has a good guide that answers these questions. You can also find a great [tutorial video series](https://www.youtube.com/watch?v=Riy4I1gy9Bc) from Blockrock Mining on how to get started

In general, the "pseaudocode" for entering things on Factom is simple:

1. Get a Factoid address ([Command Line Interface](https://docs.factom.com/cli#newfctaddress), optional)
2. Get Entry Credit Address ([Command Line Interface](https://docs.factom.com/cli#newecaddress))
3. Load Entry Credit Address (By Burning Factoids, faucet, or purchasing them)
4. Use Entry Credit address to spend entry credits for each KB of data you enter

Of course after steps 1 2 and 3 are completed, you can just repeat step 4 for any data you want to enter until your entry credit balance is gone.

Some other useful resources:
[Factom Datastructures](https://www.factom.com/devs/docs/guide/factom-data-structures)
[Factom Enterprise Wallet](https://docs.factom.com/#enterprise-wallet)

**Comment by PaulBernier** [comment]
@eolszewski passing a public EC address to `cli.add` is fine as long as you have that key pair stored in factom-walletd, in that case the library will take care of fetch the private part (EsXXXX) for you. So this is not the reason for the ack timeout you saw. The first reason that comes to my mind is that there was not enough EC to pay. The second possibility is that your factomd was not 100% yet synced with the network, so it accepted the request but never got an acknowledgement from the network.

**Comment by eolszewski** [comment]
Thank you all for the resources that you all have provided. I will be closing this as soon as I get through all of the documentation that you have recommended and have this up and running.

In the meantime, something which would greatly aid me would be how to use the M2 simulator with docker - right now the image in the factomd repository runs against the main network (which is not convenient for testing). Is there a way, at present, to do this?

**Comment by AlexCarrithers** [comment]
My suggestion would be to use the testnet rather than a simulator. You can sync the testnet by using the following factomd.conf example with any recent factomd version greater than v5.0.0: https://github.com/FactomProject/factomd-testnet-toolkit/blob/master/factomd.conf.EXAMPLE

If you are running factomd in Docker, factomd.conf is located at `/var/lib/docker/volumes/factom_keys/_data/factomd.conf`

If you need to delete the mainnet blockchain before starting, that is at `/var/lib/docker/volumes/communitytestnet_factomd_volume/_data/m2/`

Here is a faucet for getting testoids/EC: https://faucet.factoid.org/

And if you need more information on the testnet: http://www.factom-testnet.com/Introduction (note: that site is aimed at people running authority servers, so you will need to filter lots of extra information).

**Comment by eolszewski** [comment]
I'm trying to run this all in travis with CI/CD. Using the testnet precludes this as it warrants an unlocked and funded testnet wallet to be present in my setup - there is also the syncing time that this requires. 

Is there a better way for me to communicate with you all on this instead of through a github issue? What we're talking about certainly impacts my ability to address the issue raised, but I am really muddying the waters of this issue at this point.

**Comment by AlexCarrithers** [comment]
Yes, you will be able to get support on Discord: https://discord.gg/A7RUUa

**Comment by PaulBernier** [comment]
@eolszewski here's how you could achieve what you want:
In your CI/CD environment start a factom daemon like this: `factomd -network=LOCAL`
now you have your own little network locally, made of a single instance.
The genesis block will fund the following address: Fs3E9gV6DXsYzf7Fqx1fVBQPQXV695eP3k5XbmHEZVRLkMdD9qCK/FA2jK2HcLnRdS94dEcU27rF3meoJfpUcZPSinpb7AwQvPRY6RL1Q (private/public)
So from there you can have a bootstrap script that will buy ECs using that address (using factom-cli for instance) and then you can use that funded EC address to make your tests against your local network.

**Comment by eolszewski** [comment]
This has been resolved, thank you.
